trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Checkout the repo
  - task: Checkout@1

  # 2. Install Docker Compose (if not preinstalled)
  - script: |
      sudo apt-get update
      sudo apt-get install -y docker-compose
    displayName: 'Install Docker Compose'

  # 3. Build and start Selenium Grid
  - script: |
      docker-compose -f docker-compose.yml up -d
    displayName: 'Start Selenium Grid'

  # 4. Run your tests (example using Maven or pytest)
  - script: |
      mvn test
    displayName: 'Run Selenium Tests'

  # 5. Stop and remove containers
  - script: |
      docker-compose -f docker-compose.yml down
    displayName: 'Stop Selenium Grid'
