version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.29.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node-1:
    image: selenium/node-chrome:4.29.0
    container_name: chrome-node-1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=600
    shm_size: 2gb

  chrome-node-2:
    image: selenium/node-chrome:4.29.0
    container_name: chrome-node-2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=600
    shm_size: 2gb
